# Permalinks
#
# Setup
title:               'vilar.cc'
tagline:             'by Sergio Vilar'
description:         'vilar.cc is a blog from Sergio Vilar talking about being a better software developer'

baseurl:
url: "http://vilar.cc"

paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]
permalink: /:year/:title/

# About/contact
author:
  name:              Sérgio Vilar
  bio:               "Sergio is a software engineer from Brazil who loves to write open-source code and things about becoming a better software developer."
  location:          "Joao Pessoa, Brazil"
  url:               https://twitter.com/feelsen
  email:             vilar@Me.com

# Custom vars
version:             1.0.0
disqus: sergiovilar

collections:
  pt:
    output: true
