name: Sergio Vilar Blog
description: Blogging about development
meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://vilar.cc'
google_analytics: 'UA-65332388-1'
disqus_shortname: 'sergiovilar'

# Details for the RSS feed generator
url:            'http://vilar.cc'
author:         'Sergio Vilar'
authorTwitter:  'Feelsen'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
            disqus: true
